dist: xenial
language: go

go:
  - "1.12"

jobs:
  include:
    - name: "Unit Tests 64 bit arch"
      env: GOARCH="amd64"
    - name: "Unit Test 32 bit arch"
      env: GOARCH="386"

env:
  - GO111MODULE=on
